
  services:
    gokapi:
      image: f0rc3/gokapi:latest
      container_name: gokapi
      ports:
        - "53842:53842"
      environment:
        - TZ=UTC
      volumes:
        - ./gokapi-data:/app/data
        - ./gokapi-config:/app/config
      restart: always
  
  volumes:
    gokapi-data:
    gokapi-config: