name: Feature Request
description: Suggest an idea for Gokapi
title: "[Feature Request]"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any other ways you've thought about solving this.
      
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Anything else you would like to add to the suggestion
    validations:
      required: false

  - type: checkboxes
    id: breaking
    attributes:
      label: Impact
      options:
        - label: This would be a breaking change to existing setups.
