// Code generated by updateProtectedUrls.go - DO NOT EDIT.
package setup

// Do not modify: This is an automatically generated file created by updateProtectedUrls.go
// It contains all URLs that need to be protected when using an external authentication.

// protectedUrls contains a list of URLs that need to be protected if authentication is disabled.
// This list will be displayed during the setup
var protectedUrls = []string{"/admin", "/apiKeys", "/changePassword", "/e2eInfo", "/e2eSetup", "/logs", "/uploadChunk", "/uploadStatus", "/users"}
